joy_node:
  ros__parameters:
    dev: /dev/input/js0

joy_interface:
  ros__parameters:
    min_pwm: 1300
    max_pwm: 1700

joy_teleop:
  ros__parameters:

    vel_control:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /joy_interface/enable_pwm_control
      buttons: [5]
      service_request:
        data: False

    pwm_control:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /joy_interface/enable_pwm_control
      buttons: [4]
      service_request:
        data: True

    arm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: True
      buttons: [7]

    disarm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: False
      buttons: [6]

    manual_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: MANUAL
      buttons: [0]

    depth_hold_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: ALT_HOLD
      buttons: [1]

    guided_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: GUIDED
      buttons: [2]

    auto_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: AUTO
      buttons: [3]

    manual_control:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /joy_interface/cmd
      deadman_axes: [2]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: 0
        linear-y:
          axis: 0
          scale: 0.5
          offset: 0
        linear-z:
          axis: 4
          scale: 0.5
          offset: 0
        angular-z:
          axis: 3
          scale: 1.0
          offset: 0
